version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./database:/app/database
    environment:
      - DB_PATH=/app/database/database.db
      - GO_ENV=production
    restart: unless-stopped
